### ISSUE TITLE
How can i make a library using svelte but export react and vue component

### ISSUE THREAD

**Issue by lwyj123** [pngwn/svelte-adapter#5]
I want to write a IM component, but I need to write this component twice if I want to support Vue and React both. I am new to svelte, is this library can solve my problem?

**Comment by pngwn** [comment]
It could, yes.

You could write your svelte component and compile it (as part of your build process) and have two separate modules one using the vue adapter and one using the react adapter to wrap your components and then you could export those wrapped components instead of the svelte component (or in addition to).

**Comment by lwyj123** [comment]
It's amazing, Thank you.
